name: Serverless Automation CI/CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set environment based on branch
      run: |
        if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve -var="environment=${ENVIRONMENT}"